services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8000"
    environment:
      - DATABASE__URL=postgresql://codeant:codeant123@db:5432/codeant_db
      - SERVER__HOST=0.0.0.0
      - SERVER__PORT=8000
    depends_on:
      - db
    command: uvicorn src.codeant_agent.main:app --host 0.0.0.0 --port 8000

  # Frontend Dashboard
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=codeant
      - POSTGRES_PASSWORD=codeant123
      - POSTGRES_DB=codeant_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: