"""
Parsers - Sistema de análisis de código multi-lenguaje.

Este módulo proporciona parsers especializados para diferentes lenguajes
de programación, incluyendo análisis AST, detección de patrones y métricas.
"""

from .universal import (
    ProgrammingLanguage,
    ParseResult,
    ParserConfig,
    Parser,
    UniversalParser,
    get_universal_parser,
    initialize_parsers
)

from .universal.python_parser import (
    PythonVersion,
    PythonParserConfig,
    PythonScope,
    PythonType,
    FunctionDefinition,
    ClassDefinition,
    ImportStatement,
    PythonPattern,
    PythonMetrics,
    PythonAnalysisResult,
    PythonSemanticAnalyzer,
    PythonPatternDetector,
    PythonSpecializedParser,
    analyze_python_file,
    analyze_python_content
)

from .universal.typescript_parser import (
    JSLanguage,
    TypeScriptParserConfig,
    JSScope,
    JSType,
    JSFunctionDefinition,
    JSClassDefinition,
    JSImportStatement,
    JSExportStatement,
    JSPattern,
    JSMetrics,
    JSAnalysisResult,
    TypeScriptSemanticAnalyzer,
    TypeScriptPatternDetector,
    TypeScriptSpecializedParser,
    analyze_typescript_file,
    analyze_typescript_content
)

from .universal.rust_parser import (
    RustEdition,
    RustParserConfig,
    RustScope,
    RustType,
    RustFunctionDefinition,
    RustStructDefinition,
    RustEnumDefinition,
    RustTraitDefinition,
    RustImplBlock,
    RustImportStatement,
    RustUseStatement,
    RustOwnershipInfo,
    RustLifetimeInfo,
    RustTraitInfo,
    RustUnsafeInfo,
    RustCargoInfo,
    RustMacroInfo,
    RustPattern,
    RustMetrics,
    RustAnalysisResult,
    RustSemanticAnalyzer,
    RustPatternDetector,
    RustSpecializedParser,
    analyze_rust_file,
    analyze_rust_content
)

__all__ = [
    # Universal parser
    'ProgrammingLanguage',
    'ParseResult',
    'ParserConfig',
    'Parser',
    'UniversalParser',
    'get_universal_parser',
    'initialize_parsers',
    
    # Python parser
    'PythonVersion',
    'PythonParserConfig',
    'PythonScope',
    'PythonType',
    'FunctionDefinition',
    'ClassDefinition',
    'ImportStatement',
    'PythonPattern',
    'PythonMetrics',
    'PythonAnalysisResult',
    'PythonSemanticAnalyzer',
    'PythonPatternDetector',
    'PythonSpecializedParser',
    'analyze_python_file',
    'analyze_python_content',
    
    # TypeScript/JavaScript parser
    'JSLanguage',
    'TypeScriptParserConfig',
    'JSScope',
    'JSType',
    'JSFunctionDefinition',
    'JSClassDefinition',
    'JSImportStatement',
    'JSExportStatement',
    'JSPattern',
    'JSMetrics',
    'JSAnalysisResult',
    'TypeScriptSemanticAnalyzer',
    'TypeScriptPatternDetector',
    'TypeScriptSpecializedParser',
    'analyze_typescript_file',
    'analyze_typescript_content',
    
    # Rust parser
    'RustEdition',
    'RustParserConfig',
    'RustScope',
    'RustType',
    'RustFunctionDefinition',
    'RustStructDefinition',
    'RustEnumDefinition',
    'RustTraitDefinition',
    'RustImplBlock',
    'RustImportStatement',
    'RustUseStatement',
    'RustOwnershipInfo',
    'RustLifetimeInfo',
    'RustTraitInfo',
    'RustUnsafeInfo',
    'RustCargoInfo',
    'RustMacroInfo',
    'RustPattern',
    'RustMetrics',
    'RustAnalysisResult',
    'RustSemanticAnalyzer',
    'RustPatternDetector',
    'RustSpecializedParser',
    'analyze_rust_file',
    'analyze_rust_content',
    
    # Unified AST System
    'UnifiedAST',
    'UnifiedNode',
    'UnifiedNodeType',
    'SemanticNodeType',
    'UnifiedValue',
    'TypedValue',
    'UnifiedPosition',
    'UnifiedType',
    'Parameter',
    'UnifiedASTMetadata',
    'UnifiedSemanticInfo',
    'CrossLanguageMapping',
    'ASTId',
    'NodeId',
    'ASTVersion',
    'ASTUnifier',
    'LanguageUnifier',
    'UnificationConfig',
    'UnificationError',
    'PythonUnifier',
    'TypeScriptUnifier',
    'JavaScriptUnifier',
    'RustUnifier',
    'CrossLanguageAnalyzer',
    'CrossLanguageAnalysis',
    'SimilarPattern',
    'ConceptMapping',
    'ProgrammingConcept',
    'TranslationSuggestion',
    'CrossLanguageAntiPattern',
    'BestPractice',
    'LanguageMigration',
    'UnifiedQueryEngine',
    'UnifiedQuery',
    'QueryType',
    'QueryFilter',
    'QueryProjection',
    'QueryAggregation',
    'QueryResult',
    'CrossLanguageQueryResult',
    'QueryError',
    'CrossLanguagePatternMatcher',
    'Pattern',
    'PatternTemplate',
    'NodePattern',
    'PatternQuantifier',
    'PatternMatch',
    'CrossLanguagePatternMatch',
    'PatternError',
    'ComparisonEngine',
    'ComparisonResult',
    'CodeDifference',
    'DifferenceType',
    'DifferenceImpact',
    'CrossLanguageComparison',
    'ComparisonError',
    'SemanticNormalizer',
    'ConceptMapper',
    'TypeUnifier',
    'CrossLanguageMapper',
]
